version: '3'
services:
  server:
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/
    container_name: server
    restart: always
    build: ./server
    ports:
      - '9080:3000'
    depends_on:
      - mongodb
    volumes: ['./server:/usr/src/app']
  mongodb:
    container_name: mongodb
    image: mongo:3.2.6
    build: ./server/db
    ports:
      - '27017:27017'
  swaggerui:
    environment:
      - BASE_URL=/swagger
      - API_URL=http://localhost:9080/swagger
    container_name: swaggerui
    image: swaggerapi/swagger-ui
    ports:
      - '8082:8080'
  # app:
  #   container_name: app
  #   restart: always
  #   build: ./app
  #   ports:
  #     - '80:80'
  #   links:
  #     - server
  #   depends_on:
  #     - server
  #   volumes: ['./app:/usr/src/app']