version: '3'
services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - '9080:3000'
    depends_on:
      - mongodb
    volumes: ['./server:/usr/src/app']
  mongodb:
    container_name: mongodb
    image: mongo:3.2.6
    image: mongo
    ports:
      - '27017:27017'
  # app:
  #   container_name: app
  #   restart: always
  #   build: ./app
  #   ports:
  #     - '80:80'
  #   links:
  #     - server
  #   depends_on:
  #     - server
  #   volumes: ['./app:/usr/src/app']
  test:
    container_name: test
    build: ./test
    links:
      - server
    depends_on:
      - server
    volumes: ['./test:/usr/src/app']