# Stage 1 - the build process
FROM node:10.2.1 as build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
#RUN yarn config set strict-ssl false
RUN yarn
COPY . ./

CMD ["yarn", "start"]
# Stage 2 - the production environment
FROM nginx:1.12-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]