/**
 * Object containing all the action types
 */
const types = {
  FETCH_CAMPAIGNS_REQUESTED:      'FETCH_CAMPAIGNS_REQUESTED',
  FETCH_CAMPAIGNS_SUCCEEDED:      'FETCH_CAMPAIGNS_SUCCEEDED',
  FETCH_CAMPAIGNS_FAILED:         'FETCH_CAMPAIGNS_FAILED',
  FETCH_CAMPAIGN_BY_ID_REQUESTED: 'FETCH_CAMPAIGN_BY_ID_REQUESTED',
  FETCH_CAMPAIGN_BY_ID_SUCCEEDED: 'FETCH_CAMPAIGN_BY_ID_SUCCEEDED',
  FETCH_CAMPAIGN_BY_ID_FAILED:    'FETCH_CAMPAIGN_BY_ID_FAILED',
  SELECT_CAMPAIGN:                'SELECT_CAMPAIGN',
}

export default types