/**
 * Object containing all the action types
 */
const types = {
  FETCH_CAMPAIGNS_REQUESTED: 'FETCH_CAMPAIGNS_REQUESTED',
  FETCH_CAMPAIGNS_SUCCEEDED: 'FETCH_CAMPAIGNS_SUCCEEDED',
  FETCH_CAMPAIGNS_FAILED:    'FETCH_CAMPAIGNS_FAILED',
}

export default types